name: Branch CI
on:
  push:
    branches:
      - master
      - develop
jobs:
  package-application:
    runs-on: ubuntu-18.04
    env:
      CI: true
    if: '${{ github.actor != ''dependabot[bot]'' }}'
    steps:
      - uses: actions/checkout@v2
      - name: Setup-Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: v16.13.0
      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: ~/.m2/repository
          key: '${{ runner.os }}-maven-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Package application
        run: >-
          mvn -B package --file pom.xml
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - name: Coverage
        uses: codecov/codecov-action@v1
